- name: Verify device configuration
  hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
  - name: NSO global variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: Verify configuration data
    nso_verify:
      url: "{{ nso.url }}"
      username: "{{ nso.username }}"
      password: "{{ nso.password }}"
      data:
        snmpTemp5:snmpTemp5:
        - access: rw
          comm-str: srv_comm_2
          device:
          - c0
          - fip0
          - j0
